import './styles/index.scss'

export const metadata = {
  title: 'Portfolio de Marvin Rodrigues Novo Développeur Web',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>{children}</body>
    </html>
  )
}
